<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // 8 Produk yang sudah ada
            [
                'name' => 'Semen Tiga Roda 50kg',
                'category_id' => 1,
                'slug' => 'semen-tiga-roda-50kg',
                'stock' => 98,
                'price' => 72000,
                'is_active' => true,
                'image' => 'products/semen.jpg',
                'barcode' => 'SEMEN001',
                'description' => 'Semen berkualitas tinggi untuk konstruksi',
            ],
            [
                'name' => 'Batu Bata Merah',
                'category_id' => 2,
                'slug' => 'batu-bata-merah',
                'stock' => 1000,
                'price' => 700,
                'is_active' => true,
                'image' => 'products/bata.jpg',
                'barcode' => 'BATA001',
                'description' => 'Batu bata merah untuk dinding',
            ],
            [
                'name' => 'Besi Beton Ulir 10mm',
                'category_id' => 3,
                'slug' => 'besi-beton-ulir-10mm',
                'stock' => 200,
                'price' => 75000,
                'is_active' => true,
                'image' => 'products/besi.jpg',
                'barcode' => 'BESI001',
                'description' => 'Besi beton ulir diameter 10mm panjang 12m',
            ],
            [
                'name' => 'Pasir Bangunan 1 Karung',
                'category_id' => 4,
                'slug' => 'pasir-bangunan-1-karung',
                'stock' => 300,
                'price' => 25000,
                'is_active' => true,
                'image' => 'products/pasir.jpg',
                'barcode' => 'PASIR001',
                'description' => 'Pasir cor halus dalam karung',
            ],
            [
                'name' => 'Keramik Roman 40x40',
                'category_id' => 5,
                'slug' => 'keramik-roman-40x40',
                'stock' => 150,
                'price' => 55000,
                'is_active' => true,
                'image' => 'products/keramik.jpg',
                'barcode' => 'KERAMIK001',
                'description' => 'Keramik lantai motif polos 40x40cm',
            ],
            [
                'name' => 'Cat Tembok Dulux 5kg',
                'category_id' => 6,
                'slug' => 'cat-tembok-dulux-5kg',
                'stock' => 50,
                'price' => 98000,
                'is_active' => true,
                'image' => 'products/cat.jpg',
                'barcode' => 'CAT001',
                'description' => 'Cat tembok interior warna putih',
            ],
            [
                'name' => 'Paku 2 Inch',
                'category_id' => 7,
                'slug' => 'paku-2-inch',
                'stock' => 500,
                'price' => 15000,
                'is_active' => true,
                'image' => 'products/paku.jpg',
                'barcode' => 'PAKU001',
                'description' => 'Paku baja 2 inch untuk rangka',
            ],
            [
                'name' => 'Triplek 9mm',
                'category_id' => 8,
                'slug' => 'triplek-9mm',
                'stock' => 80,
                'price' => 75000,
                'is_active' => true,
                'image' => 'products/triplek.jpg',
                'barcode' => 'TRIPLEK001',
                'description' => 'Lembaran triplek untuk plafon dan furnitur',
            ],

            // 🔟 Tambahan 10 Produk
            [
                'name' => 'Semen Gresik 50kg',
                'category_id' => 1,
                'slug' => 'semen-gresik-50kg',
                'stock' => 180,
                'price' => 71000,
                'is_active' => true,
                'image' => 'products/semen2.jpg',
                'barcode' => 'SEMEN002',
                'description' => 'Semen Gresik kualitas premium',
            ],
            [
                'name' => 'Hebel Bata Ringan',
                'category_id' => 2,
                'slug' => 'hebel-bata-ringan',
                'stock' => 300,
                'price' => 9500,
                'is_active' => true,
                'image' => 'products/hebel.jpg',
                'barcode' => 'HEBEL001',
                'description' => 'Bata ringan hebel untuk dinding praktis',
            ],
            [
                'name' => 'Pipa PVC 3 inch',
                'category_id' => 3,
                'slug' => 'pipa-pvc-3-inch',
                'stock' => 180,
                'price' => 22000,
                'is_active' => true,
                'image' => 'products/pipa.jpg',
                'barcode' => 'PIPA001',
                'description' => 'Pipa PVC ukuran 3 inch untuk saluran air',
            ],
            [
                'name' => 'Cat Kayu & Besi Avian 1L',
                'category_id' => 6,
                'slug' => 'cat-kayu-besi-avian-1l',
                'stock' => 80,
                'price' => 48000,
                'is_active' => true,
                'image' => 'products/cat2.jpg',
                'barcode' => 'CAT002',
                'description' => 'Cat Avian untuk kayu dan besi ukuran 1 liter',
            ],
            [
                'name' => 'Kawat Bendrat 1kg',
                'category_id' => 3,
                'slug' => 'kawat-bendrat-1kg',
                'stock' => 120,
                'price' => 20000,
                'is_active' => true,
                'image' => 'products/kawat.jpg',
                'barcode' => 'KAWAT001',
                'description' => 'Kawat bendrat gulungan 1kg',
            ],
            [
                'name' => 'Seng Gelombang 1,8m',
                'category_id' => 3,
                'slug' => 'seng-gelombang-1-8m',
                'stock' => 90,
                'price' => 58000,
                'is_active' => true,
                'image' => 'products/seng.jpg',
                'barcode' => 'SENG001',
                'description' => 'Seng gelombang panjang 1,8 meter',
            ],
            [
                'name' => 'Kloset Jongkok Toto',
                'category_id' => 9,
                'slug' => 'kloset-jongkok-toto',
                'stock' => 45,
                'price' => 235000,
                'is_active' => true,
                'image' => 'products/kloset.jpg',
                'barcode' => 'KLOSET001',
                'description' => 'Kloset jongkok merk Toto berkualitas',
            ],
            [
                'name' => 'Genteng Beton Flat',
                'category_id' => 4,
                'slug' => 'genteng-beton-flat',
                'stock' => 1000,
                'price' => 4500,
                'is_active' => true,
                'image' => 'products/genteng.jpg',
                'barcode' => 'GENTENG001',
                'description' => 'Genteng beton flat tahan lama',
            ],
            [
                'name' => 'Triplek 12mm',
                'category_id' => 8,
                'slug' => 'triplek-12mm',
                'stock' => 70,
                'price' => 88000,
                'is_active' => true,
                'image' => 'products/triplek2.jpg',
                'barcode' => 'TRIPLEK002',
                'description' => 'Triplek tebal 12mm kualitas bangunan',
            ],
            [
                'name' => 'Grendel Pintu Stainless',
                'category_id' => 10,
                'slug' => 'grendel-pintu-stainless',
                'stock' => 250,
                'price' => 15000,
                'is_active' => true,
                'image' => 'products/grendel.jpg',
                'barcode' => 'GRENDEL001',
                'description' => 'Grendel pintu dari bahan stainless anti karat',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }

        $this->command->info('✅ Semua produk berhasil disimpan atau diperbarui.');
    }
}
